# Generated by Django 6.0.1 on 2026-01-19 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.team')),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('is_extra', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='cricket.innings')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='cricket.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='cricket.team')),
            ],
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='cricket.match'),
        ),
    ]
